database:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: xwiki
    MYSQL_USER: xwiki
    MYSQL_PASSWORD: xwiki
    MYSQL_DATABASE: xwiki
xwiki:
  build: .
  links:
    - database:mysql
  ports:
    - "4000:8080"